credentials:
  usernames:
    CarlyB:
      email: carly_88@live.com.au
      name: Carly Barwise
      password: 'password'

cookie: 
  expiry_days: 30
  key: 'signature_key'
  name: test_cookie

preauthorized:
  emails:
  - andrew.barwise@gmail.com